name: Laravel CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Copy the SSH private key file into the runner's .ssh directory
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          cp .github/workflows/aws-adms.pem ~/.ssh/id_rsa  # Copy the private key to .ssh
          chmod 600 ~/.ssh/id_rsa  # Set correct permissions for the private key
          # Optional: Verify the key
          cat ~/.ssh/id_rsa

      # Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: 3.107.194.223  # Your EC2 instance's IP address
          username: ubuntu  # Your EC2 username
          key: ~/.ssh/id_rsa  # Path to your SSH key
          script: |
            cd /var/www/html/adms-zkteco
            git pull origin master
            composer install --no-dev --optimize-autoloader
            php artisan migrate:fresh --seed
            php artisan config:clear && php artisan cache:clear
            php artisan route:cache

