name: Laravel Deploy to EC2

on:
  push:
    branches:
      - master  # Trigger on push to 'master' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Save SSH Key
      - name: Save SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem  # Secure permissions

      # Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: private_key.pem
          script: |
            cd /var/www/html/adms-zkteco  # Change to your Laravel project directory
            git pull origin master  # Pull the latest changes
            composer install --no-dev --optimize-autoloader  # Install dependencies
            php artisan migrate:fresh --seed  # Reset database & seed data
            php artisan config:clear && php artisan cache:clear  # Clear config/cache
            php artisan route:cache  # Cache routes for better performance
