name: Laravel CI/CD

on:
  push:
    branches:
      - master  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - master  # Trigger on pull request targeting 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Run tests (Make sure tests will run correctly using the existing .env on the server)
      - name: Run tests
        run: |
          ./vendor/bin/phpunit

  # Deployment job (optional, if you want to deploy to AWS EC2 after successful tests)
  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures deployment happens after successful build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/html/adms-zkteco
            git pull origin main  # Pull the latest code without touching .env
            composer install --no-dev --optimize-autoloader  # Ensure dependencies are installed (but won't overwrite .env)
            php artisan migrate --force  # Run migrations, but .env won't change
